name: modex_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  meta: ^1.16.0
  equatable: ^2.0.7
  google_fonts: ^6.3.0
  go_router: ^16.1.0
  url_launcher: ^6.3.2
  badges: ^3.1.2
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true